name: Model Training & Evaluation 

on: [push]

jobs:
    run-cml: 
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pull-requests: write
            issues: write

        steps:
        - name: Checkout repository code
          uses: actions/checkout@v4
        
        - name: Set up Python 
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        
        - name: Set up CML
          uses: iterative/setup-cml@v2
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Train model and evaluate
          run: |
            python iris.py
        
        - name: Write CML Report to PR/ Commit
          env: 
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            echo "# ML Model Performance Summary" > report.md

            echo "'''text" >> report.md
            cat classification_report.txt >> report.md
            echo "'''" >> report.md

            echo "## Confusion Matrix" >> report.md
            echo "![](./confusion_matrix.png)" >> report.md

            cml comment create report.md
